### ISSUE TITLE
david smith, lab issues

### ISSUE THREAD

**Issue by Bl41r** [bitedgeco/portfolio#9]
Very clean and minimalistic code, overall.  It was very easy to understand everything, with bootstrap handling the heavy lifting for the effects and layout.  I put a couple of notes on the PR, one was just a broken link for bitaverage (http vs https), and the other was about having access to the projects array.  I'm not even certain it is an issue, and in fact, it may be better to do it the way you are doing it and letting the backend deal with the source information, rather than letting a user of your site have access to it.

**Comment by bitedgeco** [comment]
Thanks for the dead link alert.

Yeh that is an immediately invoked function expression (pronounced iffy). It keeps your variable out of the global scope, stops adversaries from digging into your code in the console and it acts like a document.ready for jQuery. 

I gather its standard best practice so I am surprised Code Fellows is not teaching it.
